### ISSUE TITLE
only half of values is read from the file recorded with WavePro HD

### ISSUE THREAD

**Issue by emoehr** [lobis/lecroy-scope#1]
Hello. 
I've noticed that lecroyscope.Trace() reads only half of the data  recorded with the WavePro HD scope. Reason is that the array length of the data is taken from header["wave_array_count"] instead of header["wave_array1"]. If I replace that in the reading/file.py (line 116) then everything works correctly at least for singe traces and sequences. I don't know if this is scope model specific or a general solution and weather it works for all types of data though. 

kind regards, Ekaterina

**Comment by lobis** [comment]
Hello @emoehr, thanks for posting an issue!

When I developed this library I only had a single model of oscilloscope to test it with so I guess this kind of problems were very likely. In my experience the `wave_array_count` should contain the length of the data, but it may not be true in all cases.

Originally I uploaded some files I recorded to the `tests` section, in order to verify the library works properly.

I would love if you could share some files (in the "trc" format, binary) so I could check this issue myself and see how best to fix it! (please not more than a few KB in length 🙏🏻 )

**Comment by emoehr** [comment]
Hi, I give one of the files I work with. This is a single time trace from -2 to 8 ms, 10MSa/s. Github doesn't take .trc files so I pack it into zip format. Hope this helps.
[C2--test--00001.zip](https://github.com/lobis/lecroy-scope/files/11563549/C2--test--00001.zip)

**Comment by lobis** [comment]
Thanks @emoehr , it was indeed a bug. I fixed it and published a new release, it should work now after you update (`pip install lecroyscope`).

Thanks again for reporting the bug, please free to keep reporting new bugs and even to submit PRs with fixes or new features!
